plugin:
    name: 'shohabbos.elasticsearch::lang.plugin.name'
    description: 'shohabbos.elasticsearch::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-search
    homepage: ''
permissions:
    manage_indexes:
        tab: 'Elastic search'
        label: 'Manage indexes'
navigation:
    elasticsearch-menu:
        label: 'Elastic search'
        url: shohabbos/elasticsearch/indexes
        icon: icon-search
        permissions:
            - manage_indexes
        sideMenu:
            elasticsearch-menu-indexes:
                label: indexes
                url: shohabbos/elasticsearch/indexes
                icon: icon-list-alt
                permissions:
                    - manage_indexes
